### ISSUE TITLE
[Feature] For boto3 library segragate the AWS services

### ISSUE THREAD

**Issue by dbMundada** [Privado-Inc/privado#149]
**Is your feature request related to a problem? Please describe.**
For boto3 library segragate the AWS services
https://boto3.amazonaws.com/v1/documentation/api/latest/index.html#

```
# Get the service resource
sqs = boto3.resource('sqs')

# Create the queue. This returns an SQS.Queue instance
queue = sqs.create_queue(QueueName='test', Attributes={'DelaySeconds': '5'})
```
In above example we should be able to segragate or highlight `sqs` service is getting used as `AWS SQS`

**Comment by abhstabs** [comment]
Handled as part of https://github.com/Privado-Inc/privado/pull/179

**Comment by abhstabs** [comment]
Release as part of https://github.com/Privado-Inc/privado/releases/tag/v1.3.7
