### ISSUE TITLE
[BUG] The website failes to load with "Failed to load data" at the end of the scan 

### ISSUE THREAD

**Issue by MrCsabaToth** [Privado-Inc/privado#21]
**Describe the bug**
I compiled privado from the repository. Then I scanned an Android app repository with privado. At the end of the scan a web UI on localhost:3000 is provided but it blanks out with "Failed to load data"

**To Reproduce**
1. Distro: `Devuan GNU/Linux 5 (daedalus/ceres)`. Kernel: `Linux asus 5.18.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1 (2022-06-06) x86_64 GNU/Linux`
2. I'm scanning https://github.com/CsabaConsulting/ARPhysics
3. Went through the README steps of compile from source: cloned the privado repo, installed golang, I already had docker, compiled. No error messages.
4. Authenticated myself, got the json in email
5. Bootstrapped provado with the json
6. `privado scan ARPhsyics`

**Expected behavior**
I assume the localhost:3000 should show some dashboard of the scan. It actually flashes for 100ms before the error is shown.

**Screenshots**
![Screenshot_2022-06-14_21-40-26](https://user-images.githubusercontent.com/744949/173738622-efe00d2f-74f7-4b8e-8ff2-50ef1b8b8179.png)
![Screenshot_2022-06-14_21-40-57](https://user-images.githubusercontent.com/744949/173738634-99af7cea-0d78-4124-89d2-6599d4a576a3.png)
![Screenshot_2022-06-14_21-42-12](https://user-images.githubusercontent.com/744949/173738642-a95dfbde-5c05-4f48-99b1-9f2ffe5450de.png)
![Screenshot_2022-06-14_21-43-12](https://user-images.githubusercontent.com/744949/173738651-81c67890-5881-4a2c-bfd3-47903d240114.png)

**Additional context**
I don't think it's the particular Android app. Looks like a Django instance is running inside the Docker and the DATABASE is not configured? I don't see a configuration file for that the first blink.

**Comment by MrCsabaToth** [comment]
Here is the scan run:
```
csaba@asus:~/repos/privado$ ./privado scan ../AR/ARPhysics
> Scanning directory: /home/csaba/repos/AR/ARPhysics

> Pulling the latest image: public.ecr.aws/privado/cli:latest
latest: Pulling from privado/cli
Digest: sha256:55840ca78e35e2fe5a6646a16065c744455ec002aa337345345883eb9ed54726
Status: Image is up to date for public.ecr.aws/privado/cli:latest

> Starting container with the latest image
> Container ID: f2fbe2be05877defb6914c7e36150abf771699f3cc2d29756cc63ed19404c501

> Waiting for process to complete:
( ●    ) Scanning repository.. (89/-)               
> Complete
> Total Time taken: 90.041372608 seconds

> Scanning Complete
> Results and reports can be viewed on http://localhost:3000

> Press CTRL+C anytime to terminate the process
> Don't forget to save your changes before you exit
```

**Comment by ojaswa1942** [comment]
Thanks for opening this up.
Will get back after an initial investigation.

**Comment by ojaswa1942** [comment]
@MrCsabaToth  Can you please share a snapshot of the `Headers` tab in the dev tools as well? 
I want to make sure the request is like it is supposed to be.

**Comment by MrCsabaToth** [comment]
Good news! This was actually an interference with my other development work. I use the target default browser for various web development as well, including Django (port 8000), jekyll (port 4000), and so on. I suspect that either some service workers or simply the cache, session mechanisms for these other development interfered for the same domain (localhost). I opened the dashboard in a Private window and it shows properly:
![Screenshot_2022-06-14_22-05-16](https://user-images.githubusercontent.com/744949/173740688-d3738f0d-d019-4682-94dc-1a373a118b69.png)
Now, it's a little weird that nothing was founds since this AR app as camera permissions and I suspected that ARCore may communicate stuff, but that's another thing.

**Comment by MrCsabaToth** [comment]
For completeness, the headers in the erroring window:
![Screenshot_2022-06-14_22-08-17](https://user-images.githubusercontent.com/744949/173741005-d2867f52-884f-43ab-9762-8ecd880a4d84.png)

**Comment by MrCsabaToth** [comment]
Here is the cookies, could that session carried over from my other Django projects, or something other caused this? Pretty weird that DATABASE though:
![Screenshot_2022-06-14_22-10-13](https://user-images.githubusercontent.com/744949/173741478-ef4ce03a-59ab-4814-9540-307155fc6fd7.png)

Here is the full Django debug error page:
[ImproperlyConfigured at _api_reports_pii_.html.zip](https://github.com/Privado-Inc/privado/files/8905846/ImproperlyConfigured.at._api_reports_pii_.html.zip)

**Comment by ojaswa1942** [comment]
That's great! The internal Django app does not actually use any database and it was weird for it to throw a database-configuration error. I do think some cache or local data might have carried over and caused this. Let us know if this repeatedly bothers you and we can have a deeper look. 

Regarding the scan results, we are constantly working to improve the PII detection. At the same time, we are gradually expanding support to include more third parties. That being said, we will validate support for ARCore (cc: @vaibhavantil1).

For the time being, I hope this helps: https://developers.google.com/ar/develop/privacy-requirements.

**Comment by MrCsabaToth** [comment]
Now that I know this I'm good. I suspect other developers who may also into full-stack and have websites developed on localhost could run into this. It's an interference.

**Comment by ojaswa1942** [comment]
And oh, you can also change the `privado` port using `-p` flag (default: 3000), which should avoid the issue altogether.

**Comment by MrCsabaToth** [comment]
I don't think it's the port, I don't develop anything on the port 3000. It's simply that the session and cookies are domain based only and all the projects on various ports collide.

**Comment by ojaswa1942** [comment]
@vaibhavantil1 The original issue here is resolved. Closing in favor of #26.
