### ISSUE TITLE
[BUG] Incorrect Square SDK element

### ISSUE THREAD

**Issue by mathieudebrito** [Privado-Inc/privado#23]
**Describe the bug**
In my app, I use some square libraries (Otto, Picasso, etc) and the tool think I'm using the Square SDK and need the purchase history

**To Reproduce**
1. Scan an empty app using a square library like Otto or Picasso
2. See that the generated report include the "purchase history"

**Expected behavior**
"Purchase history" should not appear in the reports

**Desktop (please complete the following information):**
 - OS: MacOs 12.1
 - Browser Chrome
 - Version 102.0.5005.61 (Build officiel) (x86_64)

**Comment by ojaswa1942** [comment]
Thanks for reporting @mathieudebrito. 
We will look into it. Meanwhile, marking that occurrence as a false positive should solve the problem for you.

cc: @dbMundada @vaibhavantil1

**Comment by mathieudebrito** [comment]
Thank you @ojaswa1942 I did mark it as false positive, but it's still in the final report :p

**Comment by ojaswa1942** [comment]
I see, let's resolve #22 first.

**Comment by ojaswa1942** [comment]
@mathieudebrito can you try scanning Square libraries again and confirm the behavior?

**Comment by dbMundada** [comment]
Closing it as no further update from user & seems issue is fixed.

**Comment by mathieudebrito** [comment]
Sorry for the delay, it indeed fixed the issue ! 

Thank you so much guys ! 🙏
