### ISSUE TITLE
[BUG] Ports are not available: exposing port TCP 0.0.0.0:3000  address already in use

### ISSUE THREAD

**Issue by demonguru18** [Privado-Inc/privado#24]
**Describe the bug**
> Starting container with the latest image
> Container ID: 0274c8db4d8f44fae5aac464a26eb46735f60ed97f8a4b74313f5264aa06cc41
Received error: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:3000 -> 0.0.0.0:0: listen tcp 0.0.0.0:3000: bind: address already in use

**To Reproduce**
Trying to run the docker container but no success - Keep getting this error. Tried to change the port, but container wont start

**Screenshots**
![image](https://user-images.githubusercontent.com/4347612/176779725-4fa36b81-aa65-4815-9586-d9f1d9b756d1.png)

**Comment by ojaswa1942** [comment]
Thanks for reporting this @demonguru18. 

This is an error from the underlying Docker daemon while starting the container. I suspect that port `3000` is already in use on your machine. You can specify a different port using `-p` or `--port`. However, it does seem strange if you are experiencing an error with the unused port specified with the port option. 

Can you specify a different port and share the output?

**Comment by ojaswa1942** [comment]
The error is non-reproducible when run with an available port.    
Closing the issue due to inactivity - feel free to comment and reopen the issue if you continue to encounter the issue.
