### ISSUE TITLE
[BUG] App: Encountered error: Exception

### ISSUE THREAD

**Issue by jkozal** [Privado-Inc/privado#25]
command
~/.privado/bin/privado scan <repo> ends up with undescribed exception

Status: Image is up to date for public.ecr.aws/privado/cli:latest

> Starting container with the latest image
> Container ID: xxx

> Waiting for process to complete:
(   ●  ) Scanning repository.. (3/-) 
> Some error occurred
Find more details below:
 App: Encountered error:  Exception. Feel free to open an issue or contact support@privado.ai

> If this is an unexpected output, please try again or open an issue here:  https://github.com/Privado-Inc/privado
> Terminating..

**Comment by ojaswa1942** [comment]
Hi, thanks for reporting the issue @jkozal.   
We've seen this problem in systems with insufficient available resources, which might be the case here.

Kindly run the same command with `--debug` option and share the complete output.

**Comment by jkozal** [comment]
```
(   ●  ) Scanning repository.. (0/-) App: Encountered error:  Exception. Feel free to open an issue or contact support@privado.ai
Traceback (most recent call last):
  File "app.py", line 176, in <module>
AttributeError: 'Namespace' object has no attribute 'func'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 182, in <module>
  File "app.py", line 95, in create_app
  File "app.py", line 38, in read_license
PermissionError: [Errno 1] Operation not permitted: '/tmp/license.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 204, in <module>
  File "app.py", line 132, in sendEvents
KeyError: 'ResultState'
[16] Failed to execute script 'app' due to unhandled exception!
```

**Comment by ojaswa1942** [comment]
> PermissionError: [Errno 1] Operation not permitted: '/tmp/license.json'

Alright. This is not a problem related to resources, but something permission-based.

May I know your installation method - whether it was manually installed? Also, did the command `privado bootstrap <path-to-license-file>` yield any error?

**Comment by ojaswa1942** [comment]
The error is not reproducible at our end. However, this seems like a permission-related error.   

Closing the issue due to inactivity - feel free to comment and reopen the issue if you continue to encounter this issue.
