### ISSUE TITLE
[Feature] Allow scan results to be deleted in the Cloud UI

### ISSUE THREAD

**Issue by cattius** [Privado-Inc/privado#277]
**Is your feature request related to a problem? Please describe.**
The repository scan results uploaded to the Cloud UI may contain personal data or company confidential information. For example, the repository name is by default set to the full file path of the repository on disk. This is likely to contain personal data such as the user's name and may be mistakenly uploaded, so the user should be able to delete this data. I think the risk of this data being mistakenly uploaded is high, particularly when a user tests out Privado for the first time.

**Describe the solution you'd like**
There is a delete button available in the cloud UI (https://community.privado.ai/repositories) that permanently deletes a scanned project. 
(I realize this isn't implemented in this repo, but as this tool uploads the results, this seemed like an appropriate place to file an issue.)

**Additional context**
The only option I see in the UI is to "View", and the details page also does not have a delete option. Currently it seems the only way to get the scan deleted would be to email the Privado privacy contact email and request deletion of all personal information, exercising one's data subject rights under data protection law. This would entail deleting the entire account - whereas the user may just wish to delete a single mistakenly uploaded repository - and not all users live in jurisdictions where they have these rights.

**Comment by prashant-privado** [comment]
Thanks @cattius. We'll check this.

**Comment by prashant-privado** [comment]
@cattius We have picked this, should be available in next 2 weeks.

**Comment by vishesh27k** [comment]
@cattius We have added support for removing repository scan results.
