### ISSUE TITLE
Java crash and does not complete an analysis

### ISSUE THREAD

**Issue by SecurityGuyPro** [Privado-Inc/privado#300]
**Describe the bug**
A run of privado against the current source of openmrs-core does not complete and ends with a number of java stack traces during the code scanning phase.

**To Reproduce**
Download the current openmrs-core source from: https://github.com/openmrs/openmrs-core
unzip the source
run privado against the directory: privado scan openmrs-core-master

**Expected behavior**
I would expect a complete run like one receives with the BankingSystem-Backend-master example given.

**Screenshots**

[privado_output.txt](https://github.com/Privado-Inc/privado/files/12486211/privado_output.txt)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 23.04 patched as of August 31 2023

**Additional context**

**Comment by SecurityGuyPro** [comment]
I would also like to add that I did reproduce this on MacOS v13.5.1 with docker 4.21.1.

**Comment by khemrajrathore** [comment]
@SecurityGuyPro  After analysing, found a piece of code in `databaseReadPass` which is a resource-intensive task and becomes a bottleneck for repos like `openmrs-core` . Currently have added a flag `disable-read-dataflow` to be able to get the repo scanned on a laptop.

The default behaviour is to run the read dataflow, but for repos that need a higher configuration `disable-read-dataflow` can be used to skip the intensive task

The optimized version will be available in a follow-up PR

To use the flag, follow the step
- Update privado `privado update` (as the flag will be available from version 2.2.6)
- Run scan `privado scan openmrs-core --enable-experiments --disable-read-dataflow`

PR which adds `disable-read-dataflow` can be found [here](https://github.com/Privado-Inc/privado-core/pull/709)

**Comment by ojaswa1942** [comment]
Thanks for the quick resolution @khemrajrathore 🎉

**Comment by SecurityGuyPro** [comment]
Thank you @khemrajrathore.
Just out of curiosity, why not (if the condition of the read-dataflow fails like in the problem report) set a flag for tracking purposes and then perform a second try with the disable-read-dataflow. Then at the final output report that an operation on xxx failed and was retried without the read-dataflow. It would require less interaction in the event of a fault.

**Comment by khemrajrathore** [comment]
Thanks @SecurityGuyPro Will definitely look at adding these to the testing pipeline
