### ISSUE TITLE
Keeps cutting off WIFI after loging out.

### ISSUE THREAD

**Issue by KPreston2900050** [Privado-Inc/privado#390]
I use Windows 11
6G WIFI WPA3 Personal

It works as expected, cuts internet when dropped, the usual.
Actually, that is another thing.
If I am on the same network and accessing my PC remotely from another, If Privado does cut out then it will not restore my remote connection.  This causes me to go to the remote computer using Privado, logging in and dropping the cut off switch until I can restore the remote connection.  That is asinine and a blatant disregard for security.

Regardless.  This complaint is more frequent and specific.

I log out and the service continues to run in the background for some reason.
When it is running without the app, it cuts the wifi intermittently until I stop it.

Put it this way.
Once I exit Privado after a session then this thing has no business running or doing anything especially dropping my WIFI access.
It should not be doing things for my own good, providing benign diagnostic information or even calling mom to say hello.

I have used Privado for around 8 years now.
It is my hope that this software gets fixed so I do not have to give a rival another look.
My subscription is almost up for renewal so I have options at this point.

**Comment by tuxology** [comment]
@KPreston2900050 I guess you have reached the wrong "Privado" 😉 We are a privacy scanning solution not the VPN
