### ISSUE TITLE
upgrade phone rule to get only phone keyword

### ISSUE THREAD

**Issue by HiteshMah-Jan** [Privado-Inc/privado#43]
**Description**
There's a small problem with the phone rule. In case the field is called phoneDetail will check correctly, but in case the field is just phone the regex would not get it

**To Reproduce**
1. Scan a repository containing a variable or a class attribute named as `phone`
2. Observe the results. There are no instances of 'phone' reported under the source -> `Data.Sensitive.ContactData.PhoneNumber` .

**Expected behavior**
`phone` should be reported as a source under `Data.Sensitive.ContactData.PhoneNumber` .

**Desktop (please complete the following information):**
 - Reproduced across all architectures and operating systems.

**Comment by HiteshMah-Jan** [comment]
@luizleite-hotmart. Created an issue for better discussions and tracking.

**Comment by luizleite-hotmart** [comment]
I changed that part of the code. I will try to find some way to test the REGEX based on some examples to help with another cases

**Comment by ojaswa1942** [comment]
The change is now available in the latest release.
