### ISSUE TITLE
The app makes an assumption that I didn’t like: it assumes that if I want the results uploaded once, then I must want them uploaded always.

### ISSUE THREAD

**Issue by pandurangpatil** [Privado-Inc/privado#48]
**Is your feature request related to a problem? Please describe.**
The app makes an assumption that I didn’t like: it assumes that if I want the results uploaded once, then I must want them uploaded always.  On the first run, the user is prompted if they want to upload the results in order to visualize them (Do you want to visualize these results on our Privacy View Cloud Dashboard? (Y/n)). Is the user selects “Y”, "syncToPrivadoCloud": true is added to ~/.privado/config.json and the user is never prompted again. In my own work environment, there are certain repos that I would never allow to leave my computer and other repos that would not be a problem.

**Describe the solution you'd like**
I suggest adding the option “always” to that prompt, and making “Y/n” apply only to the current scan.   (Maybe also consider adding CLI options like --upload-results which would skip the prompt and be more convenient for automation)

**Comment by ojaswa1942** [comment]
We can prompt for `[a]lways / [O]nly once / [n]o` 
`Only once` can be the default value. 

Also worth checking if there are any interactive prompters available (like a selection list) that we can use.

**Comment by ojaswa1942** [comment]
With #63 in place, users can use `--skip-upload` flag for corresponding scans if they do not wish to upload the result to Privado Dashboard.
