### ISSUE TITLE
Ability to sync results with cloud UI again if it fails

### ISSUE THREAD

**Issue by abhstabs** [Privado-Inc/privado#52]
Sometimes while uploading the results to the cloud UI dashboard, an error/failure is encountered. Would be great to have a command to upload the results file to the dashboard without having to run the entire scan again.

**Comment by ojaswa1942** [comment]
As per discussions, we will add a `privado upload` command to [privado-core](https://github.com/Privado-Inc/privado-core) and CLI which will facilitate a direct upload without any scan. It also facilitates a number of other use-cases.

**Comment by ojaswa1942** [comment]
Resolved by https://github.com/Privado-Inc/privado-core/pull/110, https://github.com/Privado-Inc/privado-core/pull/117, and https://github.com/Privado-Inc/privado-cli/pull/25

**Comment by abhstabs** [comment]
The command for core 

`./privado-core upload /<path>/<to>/<repo>`

The output from the core is 

```
abhinav@Abhinavs-MacBook-Pro privado-core % ./privado-core upload /Users/abhinav/Desktop/random/HelloShiftLeft

Privado CLI Version: dev
Privado Core Version: dev
Do you want to visualize these results on our Privacy View Cloud Dashboard? (Y/n)
y

> Successfully synchronized results with Privado Cloud 
> Continue to view results on: "https://t.community.privado.ai/signup/?token=somehashedvalue"
```

@ojaswa1942

**Comment by ojaswa1942** [comment]
@abhstabs Why are we asking this question on explicit `upload`? The user running the command is the consent itself, I believe?

**Comment by abhstabs** [comment]
We're using the same flow as Authentication here. If the env variable is set, we won't have this prompt. This was the output from `core`

**Comment by ojaswa1942** [comment]
I think we should change this first.

**Comment by khemrajrathore** [comment]
@abhstabs If we mention in the help description of `upload`, stating we are uploading this result to cloud. Then we don't need to ask this question again. 
we can safely assume his consent and have the same implementations as `--overwrite` in `scan` command

**Comment by pandurangpatil** [comment]
@abhstabs agree with @ojaswa1942 and @khemrajrathore that we should not ask for consent while running the upload command as the user running that command itself is the consent.

**Comment by ojaswa1942** [comment]
This is merged in `dev` branch for both [Core](https://github.com/Privado-Inc/privado-core/tree/dev) & [CLI](https://github.com/Privado-Inc/privado-cli/tree/dev). We will close this with the release.

**Comment by ojaswa1942** [comment]
`privado upload` command is now available with the latest release.
