### ISSUE TITLE
[BUG] [Documentation] Home page refers to "contribution page"

### ISSUE THREAD

**Issue by egirard** [Privado-Inc/privado#59]
**Describe the bug**
Home page https://github.com/Privado-Inc/privado#contribute describes 
"If you love this project and would like to contribute, please check out our contribution page."

Without linking to the actual page.  I was going to just submit a patch to fix it, but  can't find the actual contribution page in the docs or site.

**Comment by ojaswa1942** [comment]
Hi @egirard, sorry for the inconvenience. 
Yes, this is on our list and we're working on it.

**Comment by ojaswa1942** [comment]
Duplicate of #45
