### ISSUE TITLE
[BUG] Documentation: Privado CLI does not show local results

### ISSUE THREAD

**Issue by gnittala** [Privado-Inc/privado#60]
**Describe the bug**
The documentation screenshots for the run of the scan show the results locally, but the latest version does not show the summary locally, only the URL is provided to the user

**To Reproduce**

1. Check the screen-grab on the 'Running a scan' [page](https://docs.privado.ai/getting-started-with-privado/running-a-scan)
2. On the GIF you will see that the output of the scan results are shown
3. But checking the [source](https://github.com/Privado-Inc/privado-core/blame/e91f75f29dbe9cd409506f01f77b667d68044045/src/main/scala/ai/privado/entrypoint/ScanProcessor.scala#L330) looks like local output is no longer part of the latest. I _think_ this is the location, please review
4. So either the local output has to be enabled or the GIF needs to be updated

**Expected behavior**
The documentation should be updated to not have the summary results (or) the commented section in `ScanProcessor.scala` should be enabled

**Screenshots**
![Actual-Local-Scan-Results](https://user-images.githubusercontent.com/22971806/189560450-76b517e1-ad09-4575-8bbc-757bfd28515a.png)
![Doc-Local-Scan-Results](https://user-images.githubusercontent.com/22971806/189560452-91521369-3c7b-4c9f-baac-e4c384f43e71.png)
- Actual-Local-Scan-Results.png: The output
- Doc-Local-Scan-Results.png: The documentation

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Vivaldi 5.0
 - Version : Privado CLI Version: v2.0.1, Privado Core Version: v1.0.1, Privado Main Version: v1.0.1

**Additional context**
I ran the scan using the example _BankingSystem-Backend_ code
`./privado scan BankingSystem-Backend`

**Comment by ojaswa1942** [comment]
Hi @gnittala 
Thanks for reporting this issue. 

We are enhancing the result section, and the PR is ready. 
This will be fixed by https://github.com/Privado-Inc/privado-core/pull/123.

We also plan to make a minor release later this week, which will include these changes.

**Comment by ojaswa1942** [comment]
This has been fixed with the latest release.

@gnittala You can run `privado update` to update to the latest version of Privado OSS.

**Comment by gnittala** [comment]
Thank you @ojaswa1942  and @dbMundada. The local output now has the details of the scan. Screenshot attached. 

Should the [documentation](https://docs.privado.ai/getting-started-with-privado/running-a-scan) be updated to show the new detail ?

![issue-60-local-results](https://user-images.githubusercontent.com/22971806/190538543-cb271819-837a-4df7-b61b-494181477992.png)

**Comment by ojaswa1942** [comment]
Thanks for confirming @gnittala. 
Yes, documentation updates are in-progress and will be added incrementally after a wider feedback.
