### ISSUE TITLE
[BUG] Report PDF is blank

### ISSUE THREAD

**Issue by prashant-privado** [Privado-Inc/privado#7]
**Describe the bug**
Operating System: MacOS
Runt the Privado CLI, fill in all the sections, go to the final screen, and hit "Save as PDF".  The downloaded report is blank.

**To Reproduce**

1. Run privado scan <repo>
2.  Fill in all the sections, go to the final screen, and hit "Save as PDF"

**Expected behavior**
PDF report should be proper with all the data

**Comment by ojaswa1942** [comment]
Replicated with Chrome  
Works fine with Safari

cc @Vishesh27Kumar

**Comment by Vishesh27Kumar** [comment]
The issue is resolved now. We have changed the library used to generate pdf from the summary. Pdf report download is working for all browsers.
