### ISSUE TITLE
[Documentation]: Updated documentation to fix typos and make intent clearer

### ISSUE THREAD

**Issue by gnittala** [Privado-Inc/privado#73]
Fixed few typos on docs and also made minor additions to make the intent clearer

The pull request for review is raised [here](https://github.com/Privado-Inc/privado/pull/70)

**Comment by ojaswa1942** [comment]
Thanks for the PR @gnittala.
It looks good, will merge soon.

**Comment by ojaswa1942** [comment]
Fixed by #70
