### ISSUE TITLE
Show Sinks under Inventory even if there are no flows

### ISSUE THREAD

**Issue by HiteshMah-Jan** [Privado-Inc/privado#74]
**Is your feature request related to a problem? Please describe.**
Currently we only show sinks under inventory where there is a valid flow, this becomes a problem when we start investigating why certain flows are missing. Sometimes that could happen because source might not be tagged or if we are still improving the flow detections. Debug also becomes easier for users. 

**Describe the solution you'd like**
Show all sinks under Inventory tab with -- under flows.

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by ojaswa1942** [comment]
Tracked here: https://github.com/Privado-Inc/privado-core/pull/146

**Comment by ojaswa1942** [comment]
@abhstabs is this live on `community.privado.ai` yet?

**Comment by khemrajrathore** [comment]
No this is not live yet

**Comment by abhstabs** [comment]
This is now a part of https://github.com/Privado-Inc/privado/releases/tag/v1.2.0
