### ISSUE TITLE
[BUG] Getting error while passing a custom rule with -c flag

### ISSUE THREAD

**Issue by AnujAgrawal30** [Privado-Inc/privado#80]
**Describe the bug**
Getting an error adding a custom rules folder to the CLI.

**To Reproduce**
1. Set up a repository for the scan. In my case, I used [BankingSystem-Backend](https://github.com/saurabh-sudo/BankingSystem-Backend)
2. Add a folder named `rules` inside the repository
3. Add java.yaml file inside the `rules` folder, to add those rules in the Java scanner
4. Run the scan with command `privado scan <repo> -c <repo>/rules`
5. Once the scan starts, you get an error `ERROR ScanProcessor$: Rules path /app/external-rules is not accessible`

**Expected behavior**
I was expecting the engine will accept the custom rule and detect elements in the code scan

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Privado CLI Version: v2.1.0
 - Privado Core Version: 1.1.0
 - Privado Main Version: 1.1.0

**Comment by abhstabs** [comment]
Hi @AnujAgrawal30, 

For using custom rules, please use the directory structure defined in the repository (https://github.com/Privado-Inc/privado). You can clone/fork the repository for your custom rule structure and pass that as external rules for your scan. 

Hope this helps! 

Thank you.

**Comment by AnujAgrawal30** [comment]
This helps. Thanks, @abhstabs 
Closing the issue.
