### ISSUE TITLE
[BUG] Docker Container does not support proxy configuration or mirrors for maven repositories.

### ISSUE THREAD

**Issue by xsist10** [Privado-Inc/privado#86]
**Describe the bug**
Docker Container does not support proxy configuration or mirrors for maven repositories.

This means custom artifacts only available in local maven repositories or global ones that require proxy configurations to reach, will not be retrievable.

**To Reproduce**
1. Setup local artifactory mirror or similar
2. Push custom artifact to local mirror
3. Setup `pom.xml` in `test-folder` with dependency on custom artifact
4. Run `privado scan test-folder
7. See error in logs

**Expected behavior**
Container should use local `~/.m2/settings.xml` configuration to access 3rd party mirrors or proxies.

**Screenshots**

```
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project <project-name>:1.0.0-SNAPSHOT (/app/code/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for <project-name>:1.0.0-SNAPSHOT: Could not transfer artifact <artifact>:pom:1.6.0 from/to default (https://jfrog.<custom-repo>.com/artifactory/maven): Transfer failed for https://jfrog.<custom-repo>.com/artifactory/maven/<artifact-path>-1.6.0.pom and 'parent.relativePath' points at wrong local POM @ line 11, column 13: Unknown host jfrog.<custom-repo>.com: No address associated with hostname -> [Help 2]
[ERROR] 

```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Version: Privado CLI: Version v2.1.0 (linux-amd64)

**Comment by xsist10** [comment]
I'm aware that this is a hard one to debug as it's environmental and involves configurations outside of the container, so feel free to reach out if you need additional information/debugging.

**Comment by pandurangpatil** [comment]
@xsist10 I guess we would need more details and probably understand your environment to debug this issue.

**Comment by xsist10** [comment]
Understood. I'll close this for now as I'm busy trying out building it from source and running it locally.

**Comment by pandurangpatil** [comment]
@xsist10 thanks for trying out. Let us know if you need any help while trying it out building the source code.
