### ISSUE TITLE
[Enhancement] Add support for experimental features

### ISSUE THREAD

**Issue by abhstabs** [Privado-Inc/privado#97]
**Is your feature request related to a problem? Please describe.**
Currently the tool supports only Java as the language. It would be great if we have support for JavaScript as well.

**Comment by abhstabs** [comment]
@ojaswa1942

**Comment by ojaswa1942** [comment]
As per discussions on https://github.com/Privado-Inc/privado-cli/pull/34: 
- Add the explicit requirement of `--enable-experiments` for experimental flags
- Add `--enable-javascript` to enable the JS scan engine until wider stability

**Comment by abhstabs** [comment]
This feature is now a part of https://github.com/Privado-Inc/privado-cli/releases/tag/v2.1.2
